apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mi-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mi-backend
  minReplicas: 1        # Nunca tener menos de 1
  maxReplicas: 10       # Nunca tener más de 10 (para no gastar infinito)
  targetCPUUtilizationPercentage: 50 # Escalar si supera el 50% de CPU